All changes I made from #498
pa1nki113r/Project_Brutality pull request #501
Opened 2020-09-14 00:44 UTC by JMartinez9820

All the changes I made from my pull request with the exception of Railgun and Dead decorations changes, #498, have been re-uploaded here in response to it being reverted.

2020-09-18 11:43 UTC, JMartinez9820 commented
Update to my pull request here. After getting confirmation regarding my previous PR behind closed doors, the Railgun fixes that fixes the no ammo crash, quick scope exploit and some unloading problems is now back in.

2020-09-25 16:45 UTC, JMartinez9820 commented
Duplicate of #

2020-11-16 03:36 UTC, pa1nki113r requested changes
Resolve conflicts with baseweapon and pistol and we should be good

2020-11-16 03:41 UTC, JMartinez9820 commented
Done. Should be good to go now.

2020-11-16 17:23 UTC, pa1nki113r approved these changes

2020-11-16 17:23 UTC, merged